### ISSUE TITLE
Error when trying to run scrip on Win 7 machine

### ISSUE THREAD

**Issue by renjithsasidharan** [svent/misc#1]
Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_process_attach: Operation failed: Access is denied.

/Users/_/gitrepo/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:95:in `_open'
[-]   /Users/_/gitrepo/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:76:in `open'
[-]   /Users/*/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:104:in`decrypt_data'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:161:in `block (3 levels) in process_files'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:158:in `each'
[-]   /Users/*/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:158:in`block (2 levels) in process_files'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:154:in `map!'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:154:in `block in process_files'
[-]   /Users/*/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:138:in`each'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:138:in `process_files'
[-]   /Users/_/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:330:in `block in run'
[-]   /Users/*/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:327:in`each'
[-]   /Users/*/gitrepo/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:327:in `run'

Any idea why this happens?

**Comment by svent** [comment]
It seems that the target process could not be accessed. Do you execute this via a user process with normal privileges?

Please note that this repository only documents the initial version of this post module, it seems you are using the one from the official metasploit repository.
